In [1]:
import numpy as np

In [2]:
list=[1,2.3,5]

In [3]:
np.array(list)

array([1. , 2.3, 5. ])

In [4]:
np.array(list,list)

TypeError: Field elements must be 2- or 3-tuples, got '1'

In [5]:
np.array(list,3)

TypeError: Cannot interpret '3' as a data type

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.random.rand(4)

array([0.67771488, 0.38190421, 0.8161971 , 0.80178358])

In [9]:
np.random.rand(3,5)

array([[0.80375715, 0.47875283, 0.39704168, 0.28144338, 0.9759905 ],
       [0.25598474, 0.79872756, 0.83130078, 0.42577259, 0.21236273],
       [0.57225327, 0.33313446, 0.91664158, 0.42641671, 0.37105793]])

In [12]:
new=np.arange(0,14)

In [13]:
new

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [14]:
new.reshape(14,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13]])

In [15]:
new.reshape(1,14)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]])

In [20]:
nx=np.arange(0,14,9)

In [21]:
nx

array([0, 9])

In [24]:
slic=new[:6]

In [26]:
slic

array([0, 1, 2, 3, 4, 5])

In [27]:
slic[:]=77.6

In [28]:
slic

array([77, 77, 77, 77, 77, 77])

In [44]:
x=np.zeros((5,5))

In [45]:
for i in range(x.shape[0]):
    x[i]=i
x    


array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [47]:
x[[3,2]]

array([[3., 3., 3., 3., 3.],
       [2., 2., 2., 2., 2.]])

In [48]:
x[[4,0]]

array([[4., 4., 4., 4., 4.],
       [0., 0., 0., 0., 0.]])

In [38]:
x=[[3,5]]

In [39]:
x

[[3, 5]]

In [1]:
print(__name__)

__main__


In [4]:
arr=np.arange(1,10)

In [5]:
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [8]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr.reshape(9,1)*arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [10]:
arr*arr.reshape(9,1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [11]:
arr*arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [12]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [14]:
x=[[1,2],[3,4]]

In [15]:
y=[[1,2],[3,4]]

In [17]:
np.matmul(x,y)

array([[ 7, 10],
       [15, 22]])

In [18]:
np.matmul(arr,arr.reshape(9,1))

array([285])

In [1]:
import numpy

In [2]:
numpy.random.rand(1)

array([0.4240608])

In [3]:
import numpy as np

In [4]:
numpy.random.rand(1)

array([0.6972959])

In [5]:
np.random.rand(1)

array([0.69700828])

In [ ]:
x=3

In [2]:
x=5
x

5

asnas

In [5]:
x=3.6//2
type(x)

float

In [6]:
y=3//2
type(y)

int

In [7]:
3.6%2

1.6

In [8]:
3%2

1

In [10]:
x,y=2,3